const fs = require('fs');
const { createArr } = require('./tools/ds');

const { totalUsers } = require('./user');

const maxGroupSize = [8, 10, 15, 16, 18, 20, 24, 25];
const guideLength = [1, 2, 2, 3, 3, 3, 4];
const difficulty = ['easy', 'easy', 'easy', 'medium', 'medium', 'hard'];

const tourIds = JSON.parse(fs.readFileSync('data/tours/tourIds.json', 'utf8'));
const totalTours = tourIds.map(_id => {
    return {
        _id,
        author: totalUsers.find(u => u.tours.includes(_id))._id,
        maxGroupSize: maxGroupSize[Math.floor(Math.random() * 8)],
        difficulty: difficulty[Math.floor(Math.random() * 6)],
        name: null,
        summary: null,
        description: null,
        firstMessage: null,
        imageCover: null,
        images: [],
        price: null,
        locations: [],
        draft: false,
        guides: createArr(guideLength[Math.floor(Math.random() * guideLength.length)]).map(_ => totalUsers[Math.floor(Math.random() * totalUsers.length)]._id),
    }
})

fs.writeFileSync('data/tours/tours.json', JSON.stringify(totalTours))

module.exports = {
    totalTours
}

const tours = [
    ['paris', 'strasbourg, france', 'lyon, france', 'toulouse', 'nantes'],
    ['marseille', 'lille, france', 'dijon, france', 'rennes', 'nantes', 'paris'],
    ['bordeaux', 'strasbourg, france', 'nimes, france', 'nantes', 'nantes', 'paris'],
    ['rome, italy', 'milan, italy', 'verona, italy', 'messina, italy', 'bologna, italy', 'trieste, italy'],
    ['verona, italy', 'rome, italy', 'bologna, italy', 'modena, italy', 'lucca, italy', 'perugia, italy'],
    ['milan, italy', 'rome, italy', 'genoa, italy', 'bari, italy', 'ravena, italy'],
    ['venice, italy', 'rome, italy', 'catania, italy', 'bologna, italy', 'genona, italy', 'perugia, italy'],
    ['Sicily, italy', 'milan, italy', 'rome, italy', 'bologna, italy', 'genona, italy'],
    ['madrid, spain', 'seville, spain', 'barcelona, spain', 'salamanca, spain', 'valencia, spain', 'toledo, spain'],
    ['barcelona, spain', 'madrid, spain', 'seville, spain', 'toledo, spain', 'salamanca, spain', 'toledo, spain'],
    ['seville, spain', 'barcelona, spain', 'madrid, spain', 'toledo, spain', 'salamanca, spain'],
    ['Lisbon, portugal', 'evora, portugal', 'aveiro, portugal', 'lagos, portugal', 'tavira, portugal'],
    ['Porto, portugal', 'braga, portugal', 'lagos, portugal', 'aveiro, portugal', 'obidos, portugal'],
    ['london, united kingdom', 'glasgow, united kingdom', 'cardiff, united kingdom', 'newcastle, united kingdom', 'liverpool, united kingdom'],
    ['manchester, united kingdom', 'london, united kingdom', 'cambridge, united kingdom', 'cardiff, united kingdom', 'obidos, united kingdom'],
    ['birmingham, united kingdom', 'manchester, united kingdom', 'london, united kingdom', 'liverpool, united kingdom', 'cardiff, united kingdom'],
    ['glasgow, united kingdom', 'birmingham, united kingdom', 'manchester, united kingdom', 'london, united kingdom', 'newcastle, united kingdom'],
    ['berlin, germany', 'frankfurt, germany', 'dresden, germany', 'nuremberg, germany', 'bremen, germany', 'bonn, germany'],
    ['munich, germany', 'hamburg, germany', 'stutgard, germany', 'essen, germany', 'nuremberg, germany', 'bremen, germany'],
    ['hamburg, germany', 'frankfurt, germany', 'hamburg, germany', 'stutgard, germany'],
    ['frankfurt, germany', 'dusseldorf, germany', 'essen, germany', 'hamburg, germany', 'bremen, germany', 'aachen, germany'],
    ['dusseldorf, germany', 'frankfurt, germany', 'bonn, germany', 'stutgard, germany', 'hamburg, germany'],
    ['zurich, switzerland', 'geneva, switzerland', 'lucerne, switzerland', 'bern, switzerland', 'basel, switzerland', 'lausanne, switzerland'],
    ['geneva, switzerland', 'zurich, switzerland', 'bern, switzerland', 'montreux, switzerland', 'lugano, switzerland', 'lausanne, switzerland'],
    ['vienna, austria', 'graz, austria', 'innsbruck, austria', 'saizburg, austria'],
    ['amsterdam, netherlands', 'the hague, netherlands', 'rotterdam, netherlands', 'utrecht, netherlands', 'groningen, netherlands', 'delft, netherlands'],
    ['copenhagen, denmark', 'aarhus, denmark', 'aalborg, denmark', 'esbjerg, denmark'],
    ['helsinki, finland', 'turku, finland', 'tampere, finland', 'vandaa, finland', 'espoo, finland', 'oulu, finland'],
    ['stockholm, sweden', 'malmo, sweden', 'gothenburg, sweden', 'lund, sweden', 'linkoping, sweden', 'vasteras, sweden'],
    ['oslo, norway', 'bergen, norway', 'trondheim, norway', 'alesund, norway', 'tromso, norway', 'stavanger, norway'],
    ['warsow, poland', 'katowice, poland', 'poznan, poland', 'krakow, poland', 'torun, poland', 'lodz, poland'],
    ['krakow, poland', 'poznan, poland', 'katowice, poland', 'torun, poland', 'warsow, poland', 'gdansk, poland'],
    ['prague, czech', 'brono, czech', 'pilsen, czech', 'olomouc, czech', 'ostrava, czech'],
    ['budapest, hungary', 'pecs, hungary', 'szeged, hungary', 'miskolc, hungary', 'gyor, hungary', 'thiva, hungary'],
    ['athens, greece', 'volos, greece', 'nafplion, greece', 'thessaloniki, greece', 'kalamata, greece', 'thiva, greece'],
    ['thessaloniki, greece', 'athens, greece', 'nafplion, greece', 'kavala, greece', 'rhodes, greece', 'kalamata, greece'],
    ['pires, greece', 'kavala, greece', 'athens, greece', 'thessaloniki, greece', 'volos, greece', 'rhodes, greece'],
    ['sofia, bulgaria', 'plovdiv, bulgaria', 'stara zagora, bulgaria', 'shumen, bulgaria', 'vidin, bulgaria'],
    ['istanbul, turkey', 'sakarya, turkey', 'bursa, turkey', 'ankara, turkey', 'konya, turkey', 'adana, turkey'],
    ['adana, turkey', 'ankara, turkey', 'Capadocia, turkey', 'istanbul, turkey', 'izmir, turkey'],
    ['izmir, turkey', 'denizli, turkey', 'ankara, turkey', 'antalya, turkey'],
    ['erzurum, turkey', 'van, turkey', 'kars, siirt', 'ankara, turkey', 'konya, turkey'],
    ['batumi, georgia', 'poti, georgia', 'borjomi, georgia', 'zugdidi, georgia', 'tbilisi, georgia'],
    ['tbilisi, georgia', 'borjomi, georgia', 'telavi, georgia', 'khashuri, georgia', 'batumi, georgia'],
    ['kutaisi, georgia', 'batumi, georgia', 'gori, georgia', 'tbilisi, georgia', 'rustavi, georgia'],
    ['yerevan, armenia', 'sevan, armenia', 'dilijan, armenia', 'vanadzor, armenia', 'gyumri, armenia'],
    ['yerevan, armenia', 'garni, armenia', 'areni, armenia', 'jermuk, armenia', 'tatev, armenia'],
    ['dilijan, armenia', 'ijevan, armenia', 'sevan, armenia', 'yerevan, armenia'],
    ['gyumri, armenia', 'ashtarak, armenia', 'yerevan, armenia', 'garni, armenia', 'ararat, armenia'],
    ['baku, azerbaijan', 'sumqayit, azerbaijan', 'sheki, azerbaijan', 'ganja, azerbaijan'],
    ['kyiv, ukraine', 'odesa, ukraine', 'lviv, ukraine', 'dnipro, ukraine', 'chernivtsi, ukraine', 'donetsk, ukraine'],
    ['odesa, ukraine', 'kiv, ukraine', 'kharkiv, ukraine', 'mariupol, ukraine', 'donetsk, ukraine', 'luhansk, ukraine'],
    ['moscow, russia', 'saint petersburg, russia', 'ekaterinburg, russia', 'nizhny novgorod, russia', 'volgograd, russia'],
    ['saint petersburg, russia', 'moscow, russia', 'perm, russia', 'hamburg, russia', 'omsk, russia', 'samara, russia'],
    ['kazan, russia', 'ufa, russia', 'nizhny novgorod, russia', 'omsk, russia', 'ekaterinburg, russia', 'volgograd, russia'],
    ['vladivostok, russia', 'nizhny novgorod, russia', 'omsk, russia', 'ufa, russia', 'samara, russia', 'ekaterinburg, russia'],
    ['nizhny novgorod, russia', 'samara, russia', 'ufa, russia', 'omsk, russia', 'ekaterinburg, russia'],
    ['almaty, kazakhstan', 'nur sultan, kazakhstan', 'aktobe, kazakhstan', 'taraz, kazakhstan'],
    ['tashkent, uzbekistan', 'bukhara, uzbekistan', 'samarkand, uzbekistan'],
    ['ulaanbaatar, mongolia', 'ulaangom, mongolia', 'khovd, mongolia'],
    ['jerusalem, israel', 'tel aviv, israel', 'haifa, israel', 'bat yam, israel', 'ashkelon, israel', 'ashdod, israel'],
    ['tel aviv, israel', 'jerusalem, israel', 'haifa, israel', 'ashdod, israel', 'bat yam, israel', 'ashkelon, israel'],
    ['haifa, israel', 'ashkelon, israel', 'jerusalem, israel', 'tel aviv, israel', 'bat yam, israel', 'ashdod, israel'],
    ['amman, jordan', 'madaba, jordan', 'aqaba, jordan', 'irbid, jordan', 'al mafraq, jordan', 'zarqa, jordan'],
    ['aqaba, jordan', 'amman, jordan', 'irbid, jordan', 'madaba, jordan', 'zarqa, jordan', 'al mafraq, jordan'],
    ['beyrut, lebanon', 'tripoli, lebanon', 'sidon, lebanon'],
    ['cairo, egypt', 'giza, egypt', 'luxor, egypt', 'aswan, egypt', 'damietta, egypt', 'edfu, egypt'],
    ['alexandria, egypt', 'cairo, egypt', 'aswan, egypt', 'luxor, egypt', 'edfu, egypt', 'damietta, egypt'],
    ['giza, egypt', 'alexandria, egypt', 'cairo, egypt', 'edfu, egypt', 'luxor, egypt', 'aswan, egypt'],
    ['tehran, iran', 'mashhad, iran', 'shiraz, iran', 'tabriz, iran', 'kermanshah, iran', 'isfahan, iran'],
    ['mashhad, iran', 'tehran, iran', 'kermanshah, iran', 'isfahan, iran', 'shiraz, iran', 'tabriz, iran'],
    ['tabriz, iran', 'shiraz, iran', 'tehran, iran', 'mashhad, iran', 'kermanshah, iran', 'isfahan, iran'],
    ['dubai, UAE', 'ras al khaimah, UAE', 'abu dhabi, UAE', 'al ain, UAE', 'sharjah, UAE', 'ajman, UAE'],
    ['abu dhabi, UAE', 'al ain, UAE', 'sharjah, UAE', 'ras al khaimah, UAE', 'ajman, UAE', 'dubai, UAE'],
    ['muscat, Oman', 'seeb, Oman', 'mutrah, Oman', 'salalah, Oman'],
    ['doha, qatar', 'al wakrah, qatar', 'al rayyan, qatar', 'dukhan, qatar'],
    ['kuwait city, kuwait', 'al jahra, kuwait', 'samiya, kuwait', 'ahmadi, kuwait'],
    ['riyadh, Saudi', 'jeddah, Saudi', 'medina, Saudi', 'mecca, Saudi', 'abha, Saudi', 'al qatif, Saudi'],
    ['jeddah, Saudi', 'riyadh, Saudi', 'abha, Saudi', 'dammam, Saudi', 'medina, Saudi', 'mecca, Saudi'],
    ['medina, Saudi', 'tabuk, Saudi', 'riyadh, Saudi', 'al qatif, Saudi', 'mecca, Saudi', 'jeddah, Saudi'],
    ['mumbai, india', 'ahmedabad, india', 'bengaluru, india', 'kolkata, india', 'jaipur, india', 'hyderabad, india'],
    ['new delhi, india', 'mumbai, india', 'kolkata, india', 'hyderabad, india', 'bengaluru, india', 'jaipur, india'],
    ['kolkata, india', 'new delhi, india', 'mumbai, india', 'chennai, india', 'ahmedabad, india', 'hyderabad, india'],
    ['chennai, india', 'kolkata, india', 'new delhi, india', 'mumbai, india', 'bengaluru, india', 'jaipur, india'],
    ['bengaluru, india', 'chennai, india', 'kolkata, india', 'new delhi, india', 'mumbai, india', 'ahmedabad, india'],
    ['beijing, china', 'xiamen, china', 'shanghai, china', 'nanjing, china', 'hangzhou, china', 'harbin, china'],
    ['shanghai, china', 'beijing, china', 'nanjing, china', 'hangzhou, china', 'chongqing, china', 'harbin, china'],
    ['chongqing, china', 'nanjing, china', 'beijing, china', 'hangzhou, china', 'wuhan, china', 'shanghai, china'],
    ['wuhan, china', 'hangzhou, china', 'nanjing, china', 'beijing, china', 'shanghai, china', 'chongqing, china'],
    ['seoul, south korea', 'busan, south korea', 'ulsan, south korea', 'daegu, south korea', 'changwon, south korea', 'gwangju, south korea'],
    ['busan, south korea', 'kyoto, south korea', 'daegu, south korea', 'ulsan, south korea', 'gwangju, south korea'],
    ['tokyo, japan', 'yokohama, japan', 'hirosima, japan', 'osaka, japan', 'kyoto, japan', 'kobe, japan'],
    ['osaka, japan', 'tokyo, japan', 'nagasaki, japan', 'kobe, japan', 'yokohama, japan', 'hirosima, japan'],
    ['manila, philippines', 'pasay, philippines', 'cebu, philippines', 'quezon, philippines'],
    ['jakarta, indonesia', 'medan, indonesia', 'makassar, indonesia', 'surabaya, indonesia'],
    ['ho chi minh, vietnam', 'nha trang, vietnam', 'hue, vietnam', 'dalat, vietnam', 'hanoi, vietnam'],
    ['hanoi, vietnam', 'ho chi minh, vietnam', 'hue, vietnam', 'nha trang, vietnam', 'dalat, vietnam', 'da nang, vietnam'],
    ['frankfurt, thailand', 'dusseldorf, thailand', 'essen, thailand', 'hamburg, thailand', 'bremen, thailand', 'aachen, thailand'],
    ['frankfurt, nepal', 'dusseldorf, nepal', 'essen, nepal', 'hamburg, nepal', 'bremen, nepal', 'aachen, nepal'],
    ['frankfurt, sri lanka', 'dusseldorf, sri lanka', 'essen, sri lanka', 'hamburg, sri lanka', 'bremen, sri lanka', 'aachen, sri lanka'],
    ['frankfurt, australia', 'dusseldorf, australia', 'essen, australia', 'hamburg, australia', 'bremen, australia', 'aachen, australia'],
    ['frankfurt, australia', 'dusseldorf, australia', 'essen, australia', 'hamburg, australia', 'bremen, australia', 'aachen, australia'],
    ['frankfurt, australia', 'dusseldorf, australia', 'essen, australia', 'hamburg, australia', 'bremen, australia', 'aachen, australia'],
    ['frankfurt, australia', 'dusseldorf, australia', 'essen, australia', 'hamburg, australia', 'bremen, australia', 'aachen, australia'],
    ['frankfurt, new zealand', 'dusseldorf, new zealand', 'essen, new zealand', 'hamburg, new zealand', 'bremen, new zealand', 'aachen, new zealand'],
    ['frankfurt, senegal', 'dusseldorf, senegal', 'essen, senegal', 'hamburg, senegal', 'bremen, senegal', 'aachen, senegal'],
    ['frankfurt, ivory coast', 'dusseldorf, ivory coast', 'essen, ivory coast', 'hamburg, ivory coast', 'bremen, ivory coast', 'aachen, ivory coast'],
    ['frankfurt, kenya', 'dusseldorf, kenya', 'essen, kenya', 'hamburg, kenya', 'bremen, kenya', 'aachen, kenya'],
    ['frankfurt, tanzania', 'dusseldorf, tanzania', 'essen, tanzania', 'hamburg, tanzania', 'bremen, tanzania', 'aachen, tanzania'],
    ['frankfurt, south africa', 'dusseldorf, south africa', 'essen, south africa', 'hamburg, south africa', 'bremen, south africa', 'aachen, south africa'],
    ['frankfurt, south africa', 'dusseldorf, south africa', 'essen, south africa', 'hamburg, south africa', 'bremen, south africa', 'aachen, south africa'],
    ['frankfurt, madagascar', 'dusseldorf, madagascar', 'essen, madagascar', 'hamburg, madagascar', 'bremen, madagascar', 'aachen, madagascar'],
    ['frankfurt, canada', 'dusseldorf, canada', 'essen, canada', 'hamburg, canada', 'bremen, canada', 'aachen, canada'],
    ['frankfurt, canada', 'dusseldorf, canada', 'essen, canada', 'hamburg, canada', 'bremen, canada', 'aachen, canada'],
    ['frankfurt, canada', 'dusseldorf, canada', 'essen, canada', 'hamburg, canada', 'bremen, canada', 'aachen, canada'],
    ['frankfurt, canada', 'dusseldorf, canada', 'essen, canada', 'hamburg, canada', 'bremen, canada', 'aachen, canada'],
    ['frankfurt, mexico', 'dusseldorf, mexico', 'essen, mexico', 'hamburg, mexico', 'bremen, mexico', 'aachen, mexico'],
    ['frankfurt, mexico', 'dusseldorf, mexico', 'essen, mexico', 'hamburg, mexico', 'bremen, mexico', 'aachen, mexico'],
    ['frankfurt, mexico', 'dusseldorf, mexico', 'essen, mexico', 'hamburg, mexico', 'bremen, mexico', 'aachen, mexico'],
    ['frankfurt, mexico', 'dusseldorf, mexico', 'essen, mexico', 'hamburg, mexico', 'bremen, mexico', 'aachen, mexico'],
    ['frankfurt, cuba', 'dusseldorf, cuba', 'essen, cuba', 'hamburg, cuba', 'bremen, cuba', 'aachen, cuba'],
    ['frankfurt, cuba', 'dusseldorf, cuba', 'essen, cuba', 'hamburg, cuba', 'bremen, cuba', 'aachen, cuba'],
    ['frankfurt, dominican', 'dusseldorf, dominican', 'essen, dominican', 'hamburg, dominican', 'bremen, dominican', 'aachen, dominican'],
    ['frankfurt, puerto', 'dusseldorf, puerto', 'essen, puerto', 'hamburg, puerto', 'bremen, puerto', 'aachen, puerto'],
    ['frankfurt, costa rica', 'dusseldorf, costa rica', 'essen, costa rica', 'hamburg, costa rica', 'bremen, costa rica', 'aachen, costa rica'],
    ['frankfurt, panama', 'dusseldorf, panama', 'essen, panama', 'hamburg, panama', 'bremen, panama', 'aachen, panama'],
    ['frankfurt, venezuela', 'dusseldorf, venezuela', 'essen, venezuela', 'hamburg, venezuela', 'bremen, venezuela', 'aachen, venezuela'],
    ['frankfurt, colombia', 'dusseldorf, colombia', 'essen, colombia', 'hamburg, colombia', 'bremen, colombia', 'aachen, colombia'],
    ['frankfurt, french guiana', 'dusseldorf, french guiana', 'essen, french guiana', 'hamburg, french guiana', 'bremen, french guiana', 'aachen, french guiana'],
    ['frankfurt, brazil', 'dusseldorf, brazil', 'essen, brazil', 'hamburg, brazil', 'bremen, brazil', 'aachen, brazil'],
    ['frankfurt, brazil', 'dusseldorf, brazil', 'essen, brazil', 'hamburg, brazil', 'bremen, brazil', 'aachen, brazil'],
    ['frankfurt, brazil', 'dusseldorf, brazil', 'essen, brazil', 'hamburg, brazil', 'bremen, brazil', 'aachen, brazil'],
    ['frankfurt, brazil', 'dusseldorf, brazil', 'essen, brazil', 'hamburg, brazil', 'bremen, brazil', 'aachen, brazil'],
    ['frankfurt, argentina', 'dusseldorf, argentina', 'essen, argentina', 'hamburg, argentina', 'bremen, argentina', 'aachen, argentina'],
    ['frankfurt, argentina', 'dusseldorf, argentina', 'essen, argentina', 'hamburg, argentina', 'bremen, argentina', 'aachen, argentina'],
    ['frankfurt, argentina', 'dusseldorf, argentina', 'essen, argentina', 'hamburg, argentina', 'bremen, argentina', 'aachen, argentina'],
    ['frankfurt, peru', 'dusseldorf, peru', 'essen, peru', 'hamburg, peru', 'bremen, peru', 'aachen, peru'],
    ['frankfurt, chile', 'dusseldorf, chile', 'essen, chile', 'hamburg, chile', 'bremen, chile', 'aachen, chile'],




]